version: '3.8'
services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - DATABASE_URL=postgres://coullax:V6dUR7mhMtaO@ep-falling-unit-a282n5v9.eu-central-1.pg.koyeb.app/koyebdb?sslmode=require&pgbouncer=true&connect_timeout=10
      - DIRECT_URL=postgres://coullax:V6dUR7mhMtaO@ep-falling-unit-a282n5v9.eu-central-1.pg.koyeb.app/koyebdb?sslmode=require&connect_timeout=10