import { ApiProperty } from "@nestjs/swagger";

export class InterviewSession {
  @ApiProperty({
    description: "Interview Session ID, generated by cuid",
    nullable: false,
    required: true,
    type: "string",
    example: "2313w49-0db7-4v79-aacc-52624343bf2t",
  })
  id: string;

  @ApiProperty({
    description: "Interview ID",
    nullable: false,
    required: true,
    type: "string",
    example: "cm4quxjjs0003vuuc0arunrlf",
  })
  interviewId: string;

  @ApiProperty({
    description: "Candidate ID",
    nullable: false,
    required: true,
    type: "string",
    example: "cm4quxjjs0003vuuc0arunrlf",
  })
  candidateId: string;

  @ApiProperty({
    description: "Answers in JSON format",
    nullable: false,
    required: true,
    type: "array",
    example: [
      { question: "What is a binary tree?", answer: "answer here" },
      { question: "Solve this coding challenge.", answer: "answer here" },
    ],
  })
  responses: Array<{ question: string; answer: string }>;

  @ApiProperty({
    description: "Status of the interview session",
    nullable: false,
    required: true,
    type: "string",
    example: "PENDING",
  })
  status:  "PENDING" | "ACTIVE" | "COMPLETED" | 'ARCHIVED';

  @ApiProperty({
    description: "Start time of the interview session in ISO 8601 format",
    nullable: true,
    required: false,
    type: "string",
    format: "date-time",
    example: "2024-12-31T12:00:00Z",
  })
  startTime?: string;

  @ApiProperty({
    description: "End time of the interview session in ISO 8601 format",
    nullable: true,
    required: false,
    type: "string",
    format: "date-time",
    example: "2024-12-31T13:00:00Z",
  })
  endTime?: string;

  @ApiProperty({
    description: "Score of the interview session",
    nullable: true,
    required: false,
    type: "number",
    example: 85.5,
  })
  score?: number;

  @ApiProperty({
    description: "Answers in JSON format",
    nullable: false,
    required: true,
    type: "array",
    example: [
      { answer: "What is a binary tree?", analysis: "analysis here" },
      { answer: "Solve this coding challenge.", analysis: "analysis here" },
    ],
  })
  aiAnalysis: Array<{ answer: string; analysis: string }>;
}
