import { ApiProperty } from "@nestjs/swagger";
import { Role } from "@prisma/client";

export class Interview {
    
    @ApiProperty({
        description: "Interview ID, generated by cuid",
        nullable: false,
        required: true,
        type: "string",
        example: "2313w49-0db7-4v79-aacc-52624343bf2t",
      })
      id: string;
    
      @ApiProperty({
        description: "Company ID",
        nullable: false,
        required: true,
        type: "string",
        example: "cm4quxjjs0003vuuc0arunrlf",
      })
      companyId: string;
    
      @ApiProperty({
        description: "Title of the interview",
        nullable: false,
        required: true,
        type: "string",
        example: "Senior Engineer Interview",
      })
      title: string;
    
      @ApiProperty({
        description: "Description of the interview",
        nullable: true,
        required: false,
        type: "string",
        example: "An interview for senior software engineering candidates.",
      })
      description?: string;
    
      @ApiProperty({
        description: "Questions in JSON format",
        nullable: false,
        required: true,
        type: "array",
        example: [
          { question: "What is a binary tree?", type: "open-ended" },
          { question: "Solve this coding challenge.", type: "coding" },
        ],
      })
      questions: object;
    
      @ApiProperty({
        description: "Duration of the interview in minutes",
        nullable: false,
        required: true,
        type: "number",
        example: 60,
      })
      duration: number;
    
      @ApiProperty({
        description: "Status of the interview",
        nullable: false,
        required: true,
        type: "string",
        enum: ["DRAFT", "PUBLISHED", "COMPLETED"],
        example: "DRAFT",
      })
      status: string;
    
    
    @ApiProperty({
        description: "Created At",
        nullable: true,
        required: false,
        type: "string",
        example: "2022-01-01T00:00:00.000Z",
    })    
    createdAt?: Date; 
    
    @ApiProperty({
        description: "Updated At",
        nullable: true,
        required: false,
        type: "string",
        example: "2022-01-01T00:00:00.000Z",
    })    
    updatedAt?: Date; 
    
}



